# Generated by Django 4.1.7 on 2023-05-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0007_answer_modify_count_comment_voter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="modify_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="question",
            name="modify_count",
            field=models.IntegerField(default=0),
        ),
    ]
