# Generated by Django 4.1.7 on 2023-05-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0008_alter_answer_modify_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="modify_count",
            field=models.IntegerField(default=0),
        ),
    ]
